// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDySCWfubyrtg4CMF8p0uAIu5O4dHueGfg',
    appId: '1:1625431795:web:fb51a9783868af4e812186',
    messagingSenderId: '1625431795',
    projectId: 'plateform-univ',
    authDomain: 'plateform-univ.firebaseapp.com',
    storageBucket: 'plateform-univ.appspot.com',
    measurementId: 'G-9QCP83CVS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbresDzc5xLo2wipjEnErLHpZmVqIIrxQ',
    appId: '1:1625431795:android:c51d4060ba6f6fca812186',
    messagingSenderId: '1625431795',
    projectId: 'plateform-univ',
    storageBucket: 'plateform-univ.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxW09pcOvUfWs6-xKX4OevGQYEqAvhmuw',
    appId: '1:1625431795:ios:333824353639f632812186',
    messagingSenderId: '1625431795',
    projectId: 'plateform-univ',
    storageBucket: 'plateform-univ.appspot.com',
    iosClientId: '1625431795-jjddhc1aldf3b4b5dpb6du5pm6dm7vej.apps.googleusercontent.com',
    iosBundleId: 'com.example.plateformeUniv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxW09pcOvUfWs6-xKX4OevGQYEqAvhmuw',
    appId: '1:1625431795:ios:333824353639f632812186',
    messagingSenderId: '1625431795',
    projectId: 'plateform-univ',
    storageBucket: 'plateform-univ.appspot.com',
    iosClientId: '1625431795-jjddhc1aldf3b4b5dpb6du5pm6dm7vej.apps.googleusercontent.com',
    iosBundleId: 'com.example.plateformeUniv',
  );
}
